matrix:
    include:
      - language: scala
        scala:
          - 2.11.7
        jdk:
          - openjdk8
        script:
          - echo "Dummy Scala test"
      
      - language: julia
        julia:
          - 1.X
        script:
          - echo "Dummy Julia test"